### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by godisboy** [ningyu1991/DefectDetection#2]
Hi, I am confused about the  data augmentation.
How to do it with each defects?
Thanks.

**Comment by ningyu1991** [comment]
Sorry for the late reply!
Does Section 2.2 in the [supplemental material](https://drive.google.com/file/d/1J3suq5UnSjCZGEkrqCHTnKUPlg505p7f/view) help?

**Comment by godisboy** [comment]
Thanks for your reply. 
I have read the Section 2.2 in spp. What you mean is data augmentation for each defects?  
If so, how to deal with all of  the training data after augmentation? For example, augmented samples of **haze** and **noise**  may be in conflict with each other.
If convenient， would you please introduce the pipeline of the augmentation results in Figure 5. 
Thanks!

**Comment by ningyu1991** [comment]
Data augmentation applies separately to each defect. For example, if one image has severe haze defect and mild noise defect, it may be augmented 10 times for haze defect and 5 times for noise defect. Then for each defect, we trained with its own augmented dataset. We just shared part of the network weights across defects.

**Comment by godisboy** [comment]
Tanks very much for your answers！
